//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آگهی ای با این نام موجود است.
        /// </summary>
        public static string AdExists {
            get {
                return ResourceManager.GetString("AdExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آگهی ای یافت نشد.
        /// </summary>
        public static string AdveriseNotFound {
            get {
                return ResourceManager.GetString("AdveriseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سن نباید کمتر از 18 باشد.
        /// </summary>
        public static string AgeError {
            get {
                return ResourceManager.GetString("AgeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن همراه و یا نام کاربری تکراریست!.
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن همراه ، نام کاربری و یا کد املاک تکراریست!.
        /// </summary>
        public static string AlreadyExists2 {
            get {
                return ResourceManager.GetString("AlreadyExists2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پارامترهای ارسالی را کامل و صحیح وارد کنید..
        /// </summary>
        public static string EnterParametersCorrectlyAndCompletely {
            get {
                return ResourceManager.GetString("EnterParametersCorrectlyAndCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات املاک نمیتواند خالی باشد.
        /// </summary>
        public static string EstateInfo {
            get {
                return ResourceManager.GetString("EstateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا مجددا تلاش کنید.
        /// </summary>
        public static string GeneralErrorTryAgain {
            get {
                return ResourceManager.GetString("GeneralErrorTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response has already started, the http status code middleware will not be executed..
        /// </summary>
        public static string InvalidOperationException {
            get {
                return ResourceManager.GetString("InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکراری میباشد.
        /// </summary>
        public static string IsExists {
            get {
                return ResourceManager.GetString("IsExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یافت نشد.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور نباید کمتر از 8 حرف باشد.
        /// </summary>
        public static string PasswordMin {
            get {
                return ResourceManager.GetString("PasswordMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمزعبور باید شامل اعداد ، حروف کوچک و بزرگ و حروف خاص باشد.
        /// </summary>
        public static string PasswordQuality {
            get {
                return ResourceManager.GetString("PasswordQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمزعبور باید شامل حروف خاص باشد.
        /// </summary>
        public static string PasswordUnique {
            get {
                return ResourceManager.GetString("PasswordUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشی یافت نشد.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن امنیتی منقضی شده است.
        /// </summary>
        public static string SecurityTokenExpiredException {
            get {
                return ResourceManager.GetString("SecurityTokenExpiredException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیل نقض محدودیت کلید خارجی امکان درج یا آپدیت وجود ندارد.
        /// </summary>
        public static string SqlForeignKeyException {
            get {
                return ResourceManager.GetString("SqlForeignKeyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلیل نقض یونیک بودن بعضی از فیلدها امکان اضافه شدن و یا اپدیت وجود ندارد.
        /// </summary>
        public static string SqlUpdateException {
            get {
                return ResourceManager.GetString("SqlUpdateException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی به این بخش بدون احراز هویت امکان پذیر نیست.
        /// </summary>
        public static string UnauthorizedAccessException {
            get {
                return ResourceManager.GetString("UnauthorizedAccessException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری فعال نیست.
        /// </summary>
        public static string UserIsNotActive {
            get {
                return ResourceManager.GetString("UserIsNotActive", resourceCulture);
            }
        }
    }
}
